"use client";

import i18n from "i18next";
import { initReactI18next } from "react-i18next";

export const resources = {
  es: { translation: {
    common: { educational: "Uso educativo · Euler–Bernoulli", continuous: "Viga continua →", single: "← Un solo vano", reset: "Restablecer", add: "+ Añadir", remove: "Eliminar", custom: "Configuración personalizada", units: "Sistema de unidades", noProfessional: "Resultados orientativos. No utilizar para diseño ni verificación profesional.", guided: "Ejemplo guiado", position: "Posición", magnitude: "Magnitud", start: "Inicio", end: "Final", showHide: "Mostrar / ocultar", learnTool: "Herramienta de aprendizaje", language: "Idioma" },
    single: { eyebrow: "Calculadora de vigas isostáticas", title: "Del sistema de cargas a los diagramas.", intro: "Combina cargas puntuales, distribuidas y momentos sobre vigas simplemente apoyadas o en voladizo.", define: "Define la viga", support: "Configuración de apoyos", simple: "Simplemente apoyada", cantLeft: "Voladizo · empotramiento izquierdo", cantRight: "Voladizo · empotramiento derecho", length: "Longitud", modulus: "Módulo E", inertia: "Inercia I", points: "Cargas puntuales", distributed: "Cargas distribuidas", moments: "Momentos aplicados", noPoints: "No hay cargas puntuales.", noDistributed: "No hay cargas distribuidas.", noMoments: "No hay momentos aplicados.", initialIntensity: "Intensidad inicial", finalIntensity: "Intensidad final", direction: "Sentido", ccw: "↺ Antihorario", cw: "↻ Horario", convention: "Convención: cargas verticales hacia abajo, momentos antihorarios positivos, momento flector sagante positivo y deflexión hacia abajo negativa.", review: "Revisa los datos", reactions: "Reacciones", development: "Desarrollo del cálculo", developmentSub: "Comprueba cómo se obtiene la respuesta.", equivalent: "Resultantes equivalentes", equilibrium: "Equilibrio estático", diagramRelation: "Relación entre diagramas", boundary: "Condiciones de borde", assumptions: "Hipótesis del modelo", read: "Lee los resultados", readSub: "Los puntos destacados indican el máximo absoluto.", shear: "Fuerza cortante", bending: "Momento flector", deflection: "Deflexión", footer: "BeamLab EDU · Herramienta de aprendizaje", modify: "Modifica libremente la geometría, las cargas y los apoyos." },
    continuous: { badge: "Método matricial · v3", eyebrow: "Calculadora de vigas continuas", title: "De los vanos a la respuesta global.", intro: "Modela hasta tres vanos, define cada apoyo y observa cómo la continuidad redistribuye momentos y reacciones.", define: "Define los vanos", addSpan: "+ Añadir vano", removeSpan: "Quitar último", spanLength: "Longitud L{{number}}", supports: "Apoyos por nudo", node: "Nudo {{number}}", free: "Libre", simple: "Apoyo simple", fixed: "Empotramiento", loads: "Cargas por vano", point: "+ Puntual", distributed: "+ Distribuida", moment: "+ Momento", empty: "Añade una carga para comenzar.", span: "Vano", spanNumber: "Vano {{number}}", pointLoad: "Carga puntual", distributedLoad: "Carga distribuida", appliedMoment: "Momento aplicado", localPosition: "Posición local", initialIntensity: "Intensidad inicial", finalIntensity: "Intensidad final", convention: "Posición local: cada carga se mide desde el inicio del vano seleccionado. Los nudos comparten desplazamiento y giro.", model: "Modelo estructural", spansCount_one: "{{count}} vano", spansCount_other: "{{count}} vanos", nodesCount: "{{count}} nudos", review: "Revisa el modelo", updated: "Resultado actualizado", updatedSub: "El cálculo satisface compatibilidad y equilibrio con los datos actuales.", export: "↓ Exportar resumen", dofs: "Grados de libertad", freeDofs: "Grados libres", maxMoment: "Momento interior máximo", maxDeflection: "Flecha máxima", globalEquilibrium: "Equilibrio global", globalEquilibriumSub: "Las reacciones recuperadas compensan todas las cargas.", verified: "Verificado", verticalLoad: "Carga vertical", verticalReactions: "Reacciones verticales", matrix: "Desarrollo matricial", matrixSub: "Inspecciona el sistema que produce estos resultados.", dofTab: "1 · GDL y apoyos", systemTab: "2 · K · d = F", resultsTab: "3 · Resultados nodales", response: "Respuesta a lo largo de todos los vanos", responseSub: "Mueve el cursor para consultar una sección.", globalX: "x global", footer: "BeamLab EDU · Vigas continuas", modify: "Modifica libremente la geometría, los apoyos y las cargas." },
    examples: { single: {
      "center-point": { title: "Carga puntual centrada", description: "Caso simétrico: las reacciones son iguales y la flecha máxima aparece en el centro." },
      "offset-point": { title: "Carga puntual descentrada", description: "Permite observar cómo la cercanía a un apoyo modifica las reacciones." },
      "full-uniform": { title: "Carga uniforme completa", description: "Caso simétrico con cortante lineal y momento parabólico." },
      "partial-uniform": { title: "Carga uniforme parcial", description: "La resultante actúa en el centro del tramo realmente cargado." },
      triangular: { title: "Carga triangular", description: "Su resultante equivale al área del triángulo y actúa a un tercio del lado más intenso." },
      trapezoidal: { title: "Carga trapezoidal parcial", description: "Combina una carga uniforme y otra triangular sobre un tramo intermedio." },
      "cantilever-tip": { title: "Voladizo con carga en el extremo", description: "El empotramiento aporta una fuerza y un momento de reacción." },
      "cantilever-uniform": { title: "Voladizo con carga uniforme", description: "La magnitud del momento aumenta hacia el empotramiento." },
      "applied-moment": { title: "Momento puntual aplicado", description: "El momento produce un salto en el diagrama de momento flector." }
    }, continuous: {
      "two-equal": { title: "Dos vanos iguales · carga uniforme", description: "Caso clásico simétrico: aparece un momento negativo sobre el apoyo interior." },
      unequal: { title: "Dos vanos desiguales", description: "Permite observar cómo la rigidez relativa de cada vano redistribuye las reacciones." },
      "three-spans": { title: "Tres vanos · cargas alternadas", description: "Ejemplo asimétrico para estudiar continuidad y equilibrio global." },
      "fixed-ends": { title: "Extremos empotrados", description: "Compara la respuesta cuando los giros extremos también están restringidos." }
    } },
    tooltip: { info: "Información: {{label}}", modulus: "Mide la rigidez del material: cuanto mayor es E, menor es la deformación para una misma carga.", inertia: "Describe la rigidez geométrica de la sección respecto al eje de flexión. Depende de su forma y dimensiones.", supports: "Un apoyo simple restringe el desplazamiento vertical; un empotramiento restringe también el giro; un nudo libre no restringe ninguno.", diagrams: "La pendiente del diagrama de momento es el cortante; la curvatura de la deformada es proporcional a M/EI.", matrix: "El método de rigidez ensambla el comportamiento de cada vano en un único sistema K·d = F.", residuals: "El residual es la pequeña diferencia numérica que queda después de sumar fuerzas o momentos. Debe ser prácticamente cero." }
  } },
  en: { translation: {
    common: { educational: "Educational use · Euler–Bernoulli", continuous: "Continuous beam →", single: "← Single span", reset: "Reset", add: "+ Add", remove: "Remove", custom: "Custom configuration", units: "Unit system", noProfessional: "Indicative results only. Do not use for professional design or verification.", guided: "Guided example", position: "Position", magnitude: "Magnitude", start: "Start", end: "End", showHide: "Show / hide", learnTool: "Learning tool", language: "Language" },
    single: { eyebrow: "Statically determinate beam calculator", title: "From loads to diagrams.", intro: "Combine point loads, distributed loads and applied moments on simply supported beams or cantilevers.", define: "Define the beam", support: "Support configuration", simple: "Simply supported", cantLeft: "Cantilever · fixed at left", cantRight: "Cantilever · fixed at right", length: "Length", modulus: "Elastic modulus E", inertia: "Inertia I", points: "Point loads", distributed: "Distributed loads", moments: "Applied moments", noPoints: "No point loads.", noDistributed: "No distributed loads.", noMoments: "No applied moments.", initialIntensity: "Start intensity", finalIntensity: "End intensity", direction: "Direction", ccw: "↺ Counter-clockwise", cw: "↻ Clockwise", convention: "Convention: downward vertical loads, positive counter-clockwise moments, positive sagging bending moment and negative downward deflection.", review: "Check the input", reactions: "Reactions", development: "Calculation walkthrough", developmentSub: "See how the response is obtained.", equivalent: "Equivalent resultants", equilibrium: "Static equilibrium", diagramRelation: "Diagram relationships", boundary: "Boundary conditions", assumptions: "Model assumptions", read: "Read the results", readSub: "Highlighted points indicate the absolute maximum.", shear: "Shear force", bending: "Bending moment", deflection: "Deflection", footer: "BeamLab EDU · Learning tool", modify: "Freely modify geometry, loads and supports." },
    continuous: { badge: "Matrix method · v3", eyebrow: "Continuous beam calculator", title: "From spans to the global response.", intro: "Model up to three spans, define each support and see how continuity redistributes moments and reactions.", define: "Define the spans", addSpan: "+ Add span", removeSpan: "Remove last", spanLength: "Length L{{number}}", supports: "Supports by node", node: "Node {{number}}", free: "Free", simple: "Simple support", fixed: "Fixed support", loads: "Loads by span", point: "+ Point", distributed: "+ Distributed", moment: "+ Moment", empty: "Add a load to begin.", span: "Span", spanNumber: "Span {{number}}", pointLoad: "Point load", distributedLoad: "Distributed load", appliedMoment: "Applied moment", localPosition: "Local position", initialIntensity: "Start intensity", finalIntensity: "End intensity", convention: "Local position: each load is measured from the start of its selected span. Nodes share displacement and rotation.", model: "Structural model", spansCount_one: "{{count}} span", spansCount_other: "{{count}} spans", nodesCount: "{{count}} nodes", review: "Check the model", updated: "Results updated", updatedSub: "The calculation satisfies compatibility and equilibrium for the current input.", export: "↓ Export summary", dofs: "Degrees of freedom", freeDofs: "Free DOFs", maxMoment: "Maximum internal moment", maxDeflection: "Maximum deflection", globalEquilibrium: "Global equilibrium", globalEquilibriumSub: "Recovered reactions balance all applied loads.", verified: "Verified", verticalLoad: "Vertical load", verticalReactions: "Vertical reactions", matrix: "Matrix development", matrixSub: "Inspect the system that produces these results.", dofTab: "1 · DOFs and supports", systemTab: "2 · K · d = F", resultsTab: "3 · Nodal results", response: "Response along all spans", responseSub: "Move the cursor to inspect a section.", globalX: "global x", footer: "BeamLab EDU · Continuous beams", modify: "Freely modify geometry, supports and loads." },
    examples: { single: {
      "center-point": { title: "Centered point load", description: "Symmetric case: both reactions are equal and maximum deflection occurs at midspan." },
      "offset-point": { title: "Offset point load", description: "Shows how moving a load closer to one support changes the reactions." },
      "full-uniform": { title: "Full-span uniform load", description: "Symmetric case with a linear shear diagram and a parabolic moment diagram." },
      "partial-uniform": { title: "Partial uniform load", description: "The equivalent resultant acts at the center of the loaded segment." },
      triangular: { title: "Triangular load", description: "Its resultant equals the triangle area and acts one third of the span from the more intense end." },
      trapezoidal: { title: "Partial trapezoidal load", description: "Combines uniform and triangular loading over an intermediate segment." },
      "cantilever-tip": { title: "Cantilever with tip load", description: "The fixed support provides both a force reaction and a moment reaction." },
      "cantilever-uniform": { title: "Cantilever with uniform load", description: "The bending moment magnitude increases toward the fixed support." },
      "applied-moment": { title: "Applied concentrated moment", description: "The applied moment creates a jump in the bending-moment diagram." }
    }, continuous: {
      "two-equal": { title: "Two equal spans · uniform load", description: "Classic symmetric case with a negative moment over the interior support." },
      unequal: { title: "Two unequal spans", description: "Shows how the relative stiffness of each span redistributes the reactions." },
      "three-spans": { title: "Three spans · alternating loads", description: "An asymmetric example for studying continuity and global equilibrium." },
      "fixed-ends": { title: "Fixed end supports", description: "Compare the response when rotations at both ends are also restrained." }
    } },
    tooltip: { info: "Information: {{label}}", modulus: "Measures material stiffness: a larger E produces less deformation under the same load.", inertia: "Describes the section's geometric stiffness about the bending axis. It depends on shape and dimensions.", supports: "A simple support restrains vertical displacement; a fixed support also restrains rotation; a free node restrains neither.", diagrams: "The slope of the moment diagram is shear; the curvature of the deflected shape is proportional to M/EI.", matrix: "The stiffness method assembles each span into one global system K·d = F.", residuals: "A residual is the small numerical difference left after summing forces or moments. It should be practically zero." }
  } },
} as const;

if (!i18n.isInitialized) void i18n.use(initReactI18next).init({ resources, lng: "es", fallbackLng: "es", interpolation: { escapeValue: false } });

export default i18n;
